[package]
name = "kvs"
version = "0.1.0"
authors = ["Maxim Zhiburt <zhiburt@gmail.com>"]
description = "A key-value store"
edition = "2018"

[dev-dependencies]
assert_cmd = "0.11.0"
predicates = "1.0.0"

[dependencies]
clap = "2.33.0"
